// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdKfd4u1-Dk6VsddgeCPeVN0jYGRXmag',
    appId: '1:970293388449:web:4d152b824ba4d848b23ce0',
    messagingSenderId: '970293388449',
    projectId: 'chat-app-d727e',
    authDomain: 'chat-app-d727e.firebaseapp.com',
    storageBucket: 'chat-app-d727e.firebasestorage.app',
    measurementId: 'G-RVV1KVY8H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENfa1iyX1E-avr08JI9QU0o-nRW7XL4Q',
    appId: '1:970293388449:android:7ae49c8e29d9eac0b23ce0',
    messagingSenderId: '970293388449',
    projectId: 'chat-app-d727e',
    storageBucket: 'chat-app-d727e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtY8dqmbep7L45ilLQd-R6kyhTJDfL5ns',
    appId: '1:970293388449:ios:41d87005fbf21482b23ce0',
    messagingSenderId: '970293388449',
    projectId: 'chat-app-d727e',
    storageBucket: 'chat-app-d727e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtY8dqmbep7L45ilLQd-R6kyhTJDfL5ns',
    appId: '1:970293388449:ios:41d87005fbf21482b23ce0',
    messagingSenderId: '970293388449',
    projectId: 'chat-app-d727e',
    storageBucket: 'chat-app-d727e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
